### PR TITLE
Bump orjson to 3.7.5

### PR DESCRIPTION
**Pull request by bdraco**

### CODE REVIEW

**Comment by bdraco** [comment]
Failure is 
```
Updating crates.io index
       error: failed to get `anyhow` as a dependency of package `maturin v0.12.20 (/tmp/pip-install-cq54om1q/maturin_b57406f7b75a42439cfab203a533b482)`
       Caused by:
         failed to fetch `[https://github.com/rust-lang/crates.io-index`](https://github.com/rust-lang/crates.io-index%60)
```

**Comment by bdraco** [comment]
https://stackoverflow.com/questions/69498373/cargo-error-failed-to-get-x-as-a-dependency

seems to indicate a corrupt index file ?

**Comment by bdraco** [comment]
https://github.com/rust-lang/cargo/issues/6513

**Comment by bdraco** [comment]
https://github.com/pyca/cryptography/issues/6673

**Comment by bdraco** [comment]
https://github.com/pyca/cryptography/issues/6673#issuecomment-986323651

**Comment by bdraco** [comment]
`-v cargo-cache:/root/.cargo`

**Review by frenck — APPROVED** [review]
Thanks, @bdraco 👍

**Pull request merged**
