### PR TITLE
Add support for Python 3.13

### PR DESCRIPTION
**Pull request by cdce8p**
Waiting on a new release of `docker-base` with Python 3.13. https://github.com/home-assistant/docker-base

### CODE REVIEW

**Comment by cdce8p** [comment]
Ready once https://github.com/home-assistant/docker-base/actions/runs/11737933380 passes.

**Comment by frenck** [comment]
Drafting as the base images failed to build.

**Comment by cdce8p** [comment]
The failure for cp313 is expected.

**Review by frenck — APPROVED** [review]
Thanks, @cdce8p 👍 

../Frenck

**Pull request merged**
